# Generated by Django 5.1.2 on 2025-01-06 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cname", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("review", models.CharField(max_length=100)),
                ("pimage", models.ImageField(upload_to="images/")),
                ("slug", models.SlugField(blank=True, null=True)),
                (
                    "subcat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criticsapp.category",
                    ),
                ),
            ],
        ),
    ]
