# Generated by Django 5.1.2 on 2025-01-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productreviewapp", "0004_alter_product_added_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="review",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
