# Generated by Django 5.1.2 on 2025-01-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productreviewapp", "0005_alter_product_price_alter_product_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="comment",
            new_name="review",
        ),
    ]
