# Generated by Django 5.1.2 on 2025-01-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productreviewapp", "0006_rename_comment_review_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(null=True),
        ),
    ]
