# Generated by Django 5.1.2 on 2025-01-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productreviewapp", "0007_alter_review_rating_alter_review_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.TextField(blank=True, null=True),
        ),
    ]
