# Generated by Django 5.1.2 on 2025-01-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productreviewapp", "0009_alter_review_product_alter_review_reviewer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="image",
            new_name="rimage",
        ),
        migrations.RemoveField(
            model_name="product",
            name="review",
        ),
    ]
