# Generated by Django 5.1.2 on 2025-01-27 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productreviewapp", "0012_review_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
